"""
Default pipeline configuration — hardcoded fallback values.

Every field in the pipeline config has a default here, ensuring zero-risk
backwards compatibility. These are used:
  1. When seeding a new tenant's workflow_templates.definition
  2. As fallback when a config field is missing from the DB
"""

DEFAULT_PIPELINE_DEFINITION: dict = {
    "pipeline": {
        "stages": [
            {"key": "sales", "label": "销售跟进", "labelKey": "stageSales", "icon": "briefcase", "color": "#7c3aed", "bg": "#f5f3ff"},
            {"key": "contract", "label": "合同签订", "labelKey": "stageContract", "icon": "document-pen", "color": "#0284c7", "bg": "#e0f2fe"},
            {"key": "procurement", "label": "采购生产", "labelKey": "stageProcurement", "icon": "factory", "color": "#c2410c", "bg": "#fff7ed"},
            {"key": "booking", "label": "订舱物流", "labelKey": "stageBooking", "icon": "ship", "color": "#15803d", "bg": "#f0fdf4"},
            {"key": "shipping", "label": "发货运输", "labelKey": "stageShipping", "icon": "package", "color": "#d97706", "bg": "#fffbeb"},
            {"key": "collection", "label": "收款结算", "labelKey": "stageCollection", "icon": "money-bag", "color": "#059669", "bg": "#d1fae5"},
        ],
    },
    "statuses": {
        "values": [
            {"key": "inquiry", "label": "询盘", "color": "bg-indigo-100 text-indigo-700", "stage": "sales"},
            {"key": "new", "label": "新线索", "color": "bg-indigo-100 text-indigo-700", "stage": "sales"},
            {"key": "replied", "label": "已回复", "color": "bg-teal-100 text-teal-700", "stage": "sales"},
            {"key": "engaged", "label": "已互动", "color": "bg-teal-100 text-teal-700", "stage": "sales"},
            {"key": "qualified", "label": "已验证", "color": "bg-purple-100 text-purple-700", "stage": "sales"},
            {"key": "contacted", "label": "已联系", "color": "bg-teal-100 text-teal-700", "stage": "sales"},
            {"key": "quoted", "label": "已报价", "color": "bg-sky-100 text-sky-700", "stage": "contract"},
            {"key": "negotiating", "label": "谈判中", "color": "bg-blue-100 text-blue-700", "stage": "contract"},
            {"key": "procuring", "label": "采购中", "color": "bg-orange-100 text-orange-700", "stage": "procurement"},
            {"key": "booking", "label": "订舱中", "color": "bg-green-100 text-green-700", "stage": "booking"},
            {"key": "fulfillment", "label": "履约中", "color": "bg-amber-100 text-amber-700", "stage": "shipping"},
            {"key": "payment", "label": "收款中", "color": "bg-emerald-100 text-emerald-700", "stage": "collection"},
            {"key": "converted", "label": "已成交", "color": "bg-green-100 text-green-800", "stage": "collection"},
            {"key": "cold", "label": "冷线索", "color": "bg-gray-100 text-gray-500", "stage": None},
            {"key": "lost", "label": "已流失", "color": "bg-gray-100 text-gray-500", "stage": None},
        ],
        "status_to_stage": {
            "inquiry": "sales", "new": "sales", "replied": "sales",
            "engaged": "sales", "qualified": "sales", "contacted": "sales",
            "quoted": "contract", "negotiating": "contract",
            "procuring": "procurement",
            "booking": "booking",
            "fulfillment": "shipping",
            "payment": "collection", "converted": "collection",
        },
        "transitions": {
            "inquiry": "quoted",
            "new": "quoted",
            "replied": "quoted",
            "contacted": "quoted",
            "quoted": "negotiating",
            "negotiating": "procuring",
            "procuring": "booking",
            "booking": "fulfillment",
            "fulfillment": "payment",
            "payment": "converted",
        },
        "rank": ["new", "inquiry", "quoted", "negotiating", "fulfillment", "won"],
    },
    "operation_tasks": [
        {"code": "factory_inspection", "title": "出厂验货（厂检）", "owner_role": "业务员", "requires_attachment": True},
        {"code": "statutory_inspection", "title": "法检/商检预约与跟进", "owner_role": "单证员", "requires_attachment": True},
        {"code": "packing_details", "title": "催要货物明细并制作分箱明细", "owner_role": "单证员", "requires_attachment": True},
        {"code": "purchase_inbound", "title": "高达采购入库登记", "owner_role": "单证员", "requires_attachment": False},
        {"code": "final_payment_invoice", "title": "付尾款、发票核验与登记", "owner_role": "单证员/出纳员", "requires_attachment": True},
        {"code": "delivery_notice", "title": "送货通知签字并发送供应商", "owner_role": "业务员/单证员", "requires_attachment": True},
        {"code": "godad_billing", "title": "发货当月高达开单", "owner_role": "单证员", "requires_attachment": False},
        {"code": "goods_receipt_confirmation", "title": "确认接货数量与包装质量", "owner_role": "业务员", "requires_attachment": True},
        {"code": "customs_declaration", "title": "报关资料制作与发送货代", "owner_role": "单证员", "requires_attachment": True},
        {"code": "clearance_and_photos", "title": "确认通关并索要装箱/装船照片", "owner_role": "业务员/单证员", "requires_attachment": True},
        {"code": "shipment_notice", "title": "开船后2个工作日内制作装船通知", "owner_role": "单证员", "requires_attachment": True},
        {"code": "docs_preparation", "title": "议付单据与附件制作并发送业务员", "owner_role": "单证员", "requires_attachment": True},
        {"code": "docs_tracking", "title": "交单跟踪登记《TRACKING》", "owner_role": "单证员", "requires_attachment": True},
        {"code": "payment_followup", "title": "回款/LC到款跟进", "owner_role": "业务员/单证员/出纳员", "requires_attachment": True},
        {"code": "eta_reminder", "title": "ETA前7天到港提醒", "owner_role": "业务员", "requires_attachment": False},
        {"code": "satisfaction_survey", "title": "到港15天满意度回访", "owner_role": "业务员/单证员", "requires_attachment": False},
        {"code": "archive_evidence", "title": "电子归档与纸质归档", "owner_role": "业务员/单证员/财务", "requires_attachment": True},
    ],
    "approval_rules": [
        {
            "action": "delivery_notice",
            "conditions": [
                {"field": "sale_amount_usd", "operator": ">", "value": 300000},
                {"field": "sale_amount_cny", "operator": ">", "value": 2000000},
                {"field": "shipping_conditions_met", "operator": "==", "value": False},
            ],
            "condition_logic": "any",
            "level": "medium",
            "default_approver": "业务经理",
        },
        {
            "action": "ship_customs",
            "conditions": [
                {"field": "shipping_conditions_met", "operator": "==", "value": False},
            ],
            "condition_logic": "any",
            "level": "high",
            "approver_thresholds": [
                {"usd": 100000, "cny": 700000, "approver": "总经理（风控经理上报）"},
            ],
            "default_approver": "业务经理",
        },
        {
            "action": "release_goods",
            "conditions": [
                {"field": "outstanding_receivable_usd", "operator": ">", "value": 0},
                {"field": "outstanding_receivable_cny", "operator": ">", "value": 0},
            ],
            "condition_logic": "any",
            "level": "high",
            "approver_thresholds": [
                {"usd": 100000, "cny": 700000, "approver": "总经理（风控经理上报）"},
            ],
            "default_approver": "业务经理",
        },
    ],
    "workflow_stages": [
        {
            "key": "sales_negotiation",
            "label": "销售洽谈",
            "icon": "briefcase",
            "color": "#7c3aed",
            "bg": "#f5f3ff",
            "roles": [
                {"key": "salesperson", "label": "业务员"},
                {"key": "purchasing", "label": "采购员"},
                {"key": "sales_supervisor", "label": "业务主管"},
                {"key": "sales_manager", "label": "业务经理"},
            ],
            "steps": [
                {"key": "classify", "label": "1. 询盘归类", "desc": "与客户沟通询盘细节，按A/B/C/D级分类告知采购员。", "owner": "业务员", "type": "checklist", "builtin": True, "status": "inquiry", "status_label": "询盘"},
                {"key": "price_inquiry", "label": "2. 采购询价", "desc": "填写产品需求并提交至供应链管理，采购员完成询价后将最终报价发回。", "owner": "业务员、采购员", "type": "data_input", "builtin": True},
                {"key": "soft_offer", "label": "3. 报虚盘", "desc": "须在6小时内回复。邮件须同时抄送直属主管和业务经理。", "owner": "业务员", "type": "checklist", "builtin": True},
                {"key": "firm_offer", "label": "4. 报实盘", "desc": "货物规格/公差/材质/价格/货源/付款方式/物流均确认后方可回复实盘。", "owner": "业务员", "type": "checklist", "builtin": True, "status": "quoted", "status_label": "已报价"},
            ],
        },
        {
            "key": "contract_signing",
            "label": "签定出口合同",
            "icon": "document-pen",
            "color": "#0284c7",
            "bg": "#e0f2fe",
            "roles": [
                {"key": "salesperson", "label": "业务员"},
                {"key": "doc_clerk", "label": "单证员"},
                {"key": "sales_supervisor", "label": "业务主管"},
                {"key": "sales_manager", "label": "业务经理"},
            ],
            "steps": [
                {"key": "confirm_details", "label": "1. 确认合同细节", "desc": "与客户确认买方公司名称、地址、国家、合同数量/金额、付款方式等。", "owner": "业务员、单证员", "type": "checklist", "builtin": True, "status": "negotiating", "status_label": "谈判中"},
                {"key": "draft_contract", "label": "2. 起草销售合同", "desc": "单证员起草合同，业务员初审。", "owner": "单证员、业务员", "type": "file_upload", "builtin": True, "file_category": "contract"},
                {"key": "order_note", "label": "3. 新订单登记表", "desc": "业务员将合同预计费用填入新订单登记表并呈递给业务主管签署。", "owner": "业务员", "type": "data_input", "builtin": True},
                {"key": "sign_contract", "label": "4. 签订销售合同", "desc": "合同草稿连同新订单登记表呈递给业务主管签署并盖章。", "owner": "业务主管、业务经理", "type": "approval", "builtin": True},
                {"key": "send_contract", "label": "5. 合同会签确认", "desc": "单证员确认合同已完成双方会签，并上传双方签字合同文件。", "owner": "单证员", "type": "file_upload", "builtin": True, "file_category": "contract"},
            ],
        },
        {
            "key": "procurement",
            "label": "采购流程",
            "icon": "factory",
            "color": "#c2410c",
            "bg": "#fff7ed",
            "roles": [
                {"key": "salesperson", "label": "业务员"},
                {"key": "doc_clerk", "label": "单证员"},
                {"key": "purchasing", "label": "采购员"},
                {"key": "purchasing_manager", "label": "采购经理"},
                {"key": "cashier", "label": "出纳员"},
                {"key": "sales_supervisor", "label": "业务主管"},
                {"key": "sales_manager", "label": "业务经理"},
                {"key": "risk_manager", "label": "风控经理"},
            ],
            "steps": [
                {"key": "procurement_check", "label": "1. 判定采购条件", "desc": "定金到账，或收到清洁LC正本，或收到客户签字盖章的销售合同后方可采购。", "owner": "单证员", "type": "checklist", "builtin": True, "status": "procuring", "status_label": "采购中"},
                {"key": "confirm_supplier", "label": "2. 确认供应商", "desc": "由业务主管在供应商名录中选定供应商，告知采购经理和单证员采购意向。", "owner": "业务主管", "type": "approval", "builtin": True},
                {"key": "sign_purchase", "label": "3. 签订采购合同", "desc": "采购经理上传已签章采购合同，合同同步归档至供应商管理。", "owner": "采购经理", "type": "file_upload", "builtin": True, "file_category": "contract"},
                {"key": "pay_deposit", "label": "4. 付款（定金）", "desc": "单证员将双方签字盖章合同、对方办款资料及高达支款单呈递给财务。", "owner": "单证员、出纳员", "type": "approval", "builtin": True},
            ],
        },
        {
            "key": "booking",
            "label": "订舱流程",
            "icon": "ship",
            "color": "#15803d",
            "bg": "#f0fdf4",
            "roles": [
                {"key": "salesperson", "label": "业务员"},
                {"key": "doc_clerk", "label": "单证员"},
                {"key": "sales_supervisor", "label": "业务主管"},
                {"key": "sales_manager", "label": "业务经理"},
            ],
            "steps": [
                {"key": "freight_inquiry", "label": "1. 海运询价", "desc": "在货物备妥前10-20天订舱。须比较≥2家货代的运费及港杂。", "owner": "业务员", "type": "data_input", "builtin": True, "status": "booking", "status_label": "订舱中"},
                {"key": "booking", "label": "2. 订舱", "desc": "散货/集装箱订舱，须满足订舱条件。", "owner": "业务员、单证员", "type": "checklist", "builtin": True},
                {"key": "cost_confirm", "label": "3. 实际费用确认", "desc": "装运完成后，单证员核对费用与订舱时是否一致。", "owner": "单证员、业务员", "type": "data_input", "builtin": True},
            ],
        },
        {
            "key": "shipping",
            "label": "发货流程",
            "icon": "package",
            "color": "#d97706",
            "bg": "#fffbeb",
            "roles": [
                {"key": "salesperson", "label": "业务员"},
                {"key": "doc_clerk", "label": "单证员"},
                {"key": "cashier", "label": "出纳员"},
                {"key": "sales_supervisor", "label": "业务主管"},
                {"key": "sales_manager", "label": "业务经理"},
            ],
            "steps": [
                {"key": "labels", "label": "1. 标签确认", "desc": "单证员制作SHIPPING MARK标签样本，业务员向客户确认。", "owner": "单证员、业务员", "type": "file_upload", "builtin": True, "status": "fulfillment", "status_label": "履约中", "file_category": "shipping"},
                {"key": "inspection", "label": "2. 验货", "desc": "业务员决定是否出厂检验，执行检验并拍照留档。", "owner": "业务员", "type": "file_upload", "builtin": True, "file_category": "inspection"},
                {"key": "packing_details", "label": "3. 索要货物明细", "desc": "业务员催要货物明细，单证员制作分箱明细发送给货代。", "owner": "业务员、单证员", "type": "data_input", "builtin": True},
                {"key": "warehouse_entry", "label": "4. 高达入库登记", "desc": "收到货物明细后，单证员在高达系统上做采购入库登记。", "owner": "单证员", "type": "data_input", "builtin": True},
                {"key": "pay_balance", "label": "5. 付尾款", "desc": "单证员走付款流程，出纳员付款。", "owner": "单证员、出纳员", "type": "approval", "builtin": True},
                {"key": "delivery_notice", "label": "6. 送货通知", "desc": "打印送货通知，注明装车要求，由业务员及业务主管签字。", "owner": "业务员、业务主管", "type": "approval", "builtin": True},
                {"key": "godad_billing", "label": "7. 高达开单", "desc": "单证员在发货当月完成高达系统开单。", "owner": "单证员", "type": "data_input", "builtin": True},
                {"key": "customs", "label": "8. 报关", "desc": "单证员制作报关材料发送货代报关。", "owner": "单证员", "type": "file_upload", "builtin": True, "file_category": "shipping"},
                {"key": "clearance_photos", "label": "9. 确认通关及照片", "desc": "确认通关情况，索要装箱/装船照片。", "owner": "业务员、单证员", "type": "file_upload", "builtin": True, "file_category": "shipping"},
                {"key": "shipment_notice", "label": "10. 装船通知", "desc": "单证员在开船后2个工作日内制作装船通知。", "owner": "单证员", "type": "file_upload", "builtin": True, "file_category": "shipping"},
                {"key": "documents", "label": "11. 单据制作与交单", "desc": "单证员制作全套议付单据及附件，交单后登记跟踪。", "owner": "单证员", "type": "file_upload", "builtin": True, "file_category": "invoice"},
            ],
        },
        {
            "key": "collection",
            "label": "回款结算",
            "icon": "money-bag",
            "color": "#059669",
            "bg": "#d1fae5",
            "roles": [
                {"key": "salesperson", "label": "业务员"},
                {"key": "doc_clerk", "label": "单证员"},
                {"key": "cashier", "label": "出纳员"},
                {"key": "sales_supervisor", "label": "业务主管"},
                {"key": "sales_manager", "label": "业务经理"},
                {"key": "risk_manager", "label": "风控经理"},
                {"key": "general_manager", "label": "总经理"},
            ],
            "steps": [
                {"key": "follow_payment", "label": "1. 跟进回款", "desc": "业务员跟进非信用证回款，单证员跟进信用证回款。", "owner": "业务员、单证员", "type": "checklist", "builtin": True, "status": "payment", "status_label": "收款中"},
                {"key": "risk_delivery", "label": "2. 风险放货审批", "desc": "后TT有应收时客户要求放货属风险放货，须向业务主管、业务经理、风控经理汇报。", "owner": "单证员", "type": "approval", "builtin": True},
                {"key": "arrival_notice", "label": "3. 到港提醒", "desc": "业务员在货物到港前7天发邮件提醒客户做好接货准备。", "owner": "业务员", "type": "checklist", "builtin": True},
                {"key": "after_sales", "label": "4. 售后回访", "desc": "货物到港15天后发送客户满意度调查，跟踪使用情况和质量异议。", "owner": "业务员、单证员", "type": "checklist", "builtin": True},
                {"key": "filing", "label": "5. 档案归档", "desc": "所有单据和照片上传到微盘对应合同文件夹，纸质版存入档案柜。", "owner": "单证员、出纳员", "type": "file_upload", "builtin": True, "status": "converted", "status_label": "已成交", "file_category": "other"},
            ],
        },
    ],
    "general_statuses": [
        {"key": "new", "label": "新线索", "color": "bg-indigo-100 text-indigo-700"},
        {"key": "cold", "label": "冷线索", "color": "bg-gray-100 text-gray-500"},
        {"key": "lost", "label": "已流失", "color": "bg-gray-100 text-gray-500"},
    ],
    "file_categories": [
        {"key": "contract", "label": "合同", "color": "bg-blue-100 text-blue-700"},
        {"key": "quotation", "label": "报价单", "color": "bg-purple-100 text-purple-700"},
        {"key": "inspection", "label": "验货", "color": "bg-orange-100 text-orange-700"},
        {"key": "shipping", "label": "物流", "color": "bg-green-100 text-green-700"},
        {"key": "invoice", "label": "发票", "color": "bg-yellow-100 text-yellow-700"},
        {"key": "correspondence", "label": "函件", "color": "bg-teal-100 text-teal-700"},
        {"key": "other", "label": "其他", "color": "bg-gray-100 text-gray-600"},
    ],
    "role_mappings": {
        "业务员": "salesperson",
        "单证员": "documentation_clerk",
        "出纳员": "cashier",
        "业务经理": "sales_manager",
        "总经理（风控经理上报）": "general_manager",
    },
}
